import esbuild from "esbuild";
import { sassPlugin } from "esbuild-sass-plugin";
import { env } from "node:process";
import fs from "node:fs";

const isProd = env.NODE_ENV === "production";
const isWatch = process.argv.includes("--watch");

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const ctx = await esbuild.context({
  entryPoints: ["src/index.ts"],
  bundle: true,
  format: "cjs",
  target: "es2018",
  outfile: "main.js",
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
  ],
  sourcemap: isProd ? false : "inline",
  treeShaking: isProd,
  minify: isProd,
  banner: {
    js: banner,
  },
  define: {
    "process.env.NODE_ENV": JSON.stringify(env.NODE_ENV || "development"),
  },
  jsx: "transform",
  jsxFactory: "React.createElement",
  jsxFragment: "React.Fragment",
  plugins: [
    sassPlugin({
      type: "css-text",
      async transform(source) {
        // styles.css に出力
        fs.writeFileSync("styles.css", source);
        return "";
      },
    }),
  ],
});

if (isWatch) {
  console.log("👀 Watching for changes...");
  await ctx.watch();
} else {
  await ctx.rebuild();
  await ctx.dispose();
  console.log(isProd ? "✅ Production build complete!" : "✅ Build complete!");
}
